---
swagger: "2.0"
info:
  version: "2016-04-15T13:47:54Z"
  title: "v0"
host: "api-staging.vip2phone.net"
basePath: "/v0"
schemes:
- "https"
paths:
  /version:
    get:
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Version"
      security:
      - MainStaging: []
      - api_key: []
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
        uri: "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:129511209983:function:mypbx-rest-version-staging/invocations"
        httpMethod: "POST"
        type: "aws"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
  MainStaging:
    type: "apiKey"
    name: "X-Api-Key"
    in: "header"
    x-amazon-apigateway-authtype: "custom"
definitions:
  Version:
    type: "object"
    required:
    - "version"
    properties:
      version:
        type: "string"
        pattern: "^(\\d+\\.\\d+\\.\\d+)$"
