---
swagger: "2.0"
info:
  version: "2016-04-15T16:24:24Z"
  title: "v0"
host: "api-staging.vip2phone.net"
basePath: "/v0"
schemes:
- "https"
paths:
  /version:
    get:
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Version"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
      security:
      - MainStaging: []
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      security:
      - MainStaging: []
securityDefinitions:
  MainStaging:
    type: "apiKey"
    name: "X-Api-Key"
    in: "header"
    x-amazon-apigateway-authtype: "custom"
definitions:
  Empty:
    type: "object"
  Version:
    type: "object"
    required:
    - "version"
    properties:
      version:
        type: "string"
        pattern: "^(\\d+\\.\\d+\\.\\d+)$"
